// Personal profile and publications. Edit this file when new work is published.
window.SITE_CONTENT = {
  contact: {
    email: "limince@ahu.edu.cn",
    cv: "",
    scholar: "https://scholar.google.com/citations?user=Agfrx18AAAAJ&hl=zh-CN",
    github: "https://github.com/limince",
    orcid: "https://orcid.org/0000-0003-1341-8599",
  },
  zh: {
    metaTitle: "李民策 Mince Li · 安徽大学",
    metaDescription: "李民策，安徽大学电气工程与自动化学院讲师，研究新能源动力、智慧能量管理、先进储能与低空智能系统。",
    skipLink: "跳到主要内容",
    navAbout: "简介",
    navResearch: "研究",
    navExperience: "经历",
    navPublications: "论文",
    navContact: "联系",
    eyebrow: "能源 · 智能 · 控制",
    name: "李民策",
    initials: "ML",
    heroTitle: "讲师 · 安徽大学电气工程与自动化学院 · 中国合肥",
    heroIntro: "我目前任职于<strong>安徽大学电气工程与自动化学院</strong>，主要研究新能源动力、智慧能量管理、先进储能与低空智能系统。",
    emailLabel: "给我邮件",
    cvLabel: "个人简历",
    status: "欢迎学术交流、学生指导与科研合作",
    aboutHeading: "关于我",
    aboutParagraph1: "我于中国科学技术大学自动化系获得控制科学与工程博士学位，师从陈宗海教授，现为安徽大学电气工程与自动化学院讲师。我的研究聚焦新能源汽车、无人机与先进储能系统中的状态感知、智能决策、能量管理和优化控制。",
    aboutParagraph2: "主持国家自然科学基金青年科学基金项目（C类）和安徽省自然科学基金青年项目（C类），曾参与国家重点研发计划及国家自然科学基金面上项目。近五年发表 SCI 论文 20 余篇，并申请发明专利 10 项。",
    statPapers: "SCI 期刊论文",
    statCitations: "Google Scholar 引用",
    statPatents: "发明专利申请",
    researchHeading: "研究方向",
    researchLead: "面向新能源交通与低空智能系统，探索能源、感知、决策和控制的深度融合。",
    research: [
      {
        number: "01",
        title: "新能源动力与智慧能量管理",
        description: "面向新能源汽车与无人机，开展燃料电池混合动力系统建模、能量管理策略与容量优化配置研究。",
      },
      {
        number: "02",
        title: "先进储能与 AI 交叉应用",
        description: "聚焦燃料电池、锂电池等新型储能，结合大模型等 AI 算法，研究状态估计、故障诊断与健康管理。",
      },
      {
        number: "03",
        title: "低空智能与无人飞行系统",
        description: "围绕低空经济，研究固定翼无人机集群协同状态估计、具身智能控制与多机博弈决策。",
      },
    ],
    experienceHeading: "教育与学术经历",
    educationHeading: "教育背景",
    education: [
      {
        date: "2019.09 — 2024.06",
        title: "博士 · 控制科学与工程",
        place: "中国科学技术大学 · 自动化系",
      },
      {
        date: "2015.09 — 2019.06",
        title: "学士 · 电气工程及其自动化",
        place: "北京交通大学 · 电气工程学院",
      },
    ],
    highlightsHeading: "荣誉与学术服务",
    news: [
      { date: "2026", text: "中国仿真学会教学成果一等奖。" },
      { date: "2025", text: "ICPRE Best Paper（最佳论文奖）；担任 ICPRE 国际会议分会场主席。" },
      { date: "2024", text: "安徽大学新入职教师“精彩一课”展示汇报一等奖。" },
      { date: "荣誉", text: "中国科学院院长优秀奖；四次获得本科生、硕士生或博士生国家奖学金。" },
      { date: "服务", text: "IEEE 会员；担任 IEEE TITS、IEEE TTE、IEEE TVT、Applied Energy、RSER、EAAI 等 SCI 期刊审稿人。" },
      { date: "学会", text: "中国自动化学会系统仿真专业委员会委员、中国仿真学会仿真技术应用专业委员会委员。" },
      { date: "教学", text: "主讲《单片机原理及应用》《人工智能导论》《通信原理》《动力电池智能管理技术》。" },
    ],
    publicationsHeading: "代表性期刊论文",
    allPublications: "Google Scholar 完整列表",
    primaryGroup: "第一作者 / 通讯作者",
    collaborativeGroup: "合作论文",
    authorNote: "* 通讯作者",
    linkPaper: "论文",
    linkCode: "代码",
    linkProject: "项目",
    publications: {
      primary: [
        {
          year: "2026",
          venue: "IEEE TTE",
          title: "Robust Transfer Learning for Lithium-ion Battery Core Temperature Estimation with Limited Data",
          authors: "X. Zhang, M. Li*",
          description: "IEEE Transactions on Transportation Electrification. doi: 10.1109/TTE.2026.3725161",
          links: { paper: "https://doi.org/10.1109/TTE.2026.3725161" },
        },
        {
          year: "2026",
          venue: "IEEE TTE",
          title: "A Hybrid Deep Reinforcement-Supervised Learning Framework for Energy Management of Fuel Cell-Battery Hybrid Vehicles",
          authors: "D. Yang, H. Lv, Y. Yan, M. Li*, R. Pan, J. Liang",
          description: "IEEE Transactions on Transportation Electrification. doi: 10.1109/TTE.2026.3671072",
          links: { paper: "https://doi.org/10.1109/TTE.2026.3671072" },
        },
        {
          year: "2026",
          venue: "Applied Energy",
          title: "Toward Intelligent Energy Management for Fuel Cell Hybrid Electric Vehicles: Advances in Topologies, Perception, Decision, and Connected Systems",
          authors: "M. Li, T. Pei, T. Jiang, J. Tian, T. Pan, Y. Fan, D. Yang, X. Zhang, D. Zhang",
          description: "Applied Energy, 412, 127680.",
          links: { paper: "https://doi.org/10.1016/j.apenergy.2026.127680" },
        },
        {
          year: "2025",
          venue: "Int. J. Hydrogen Energy",
          title: "An Adaptive Fuzzy Energy Management Strategy for Fuel Cell Hybrid Vehicles Considering Soft Classification for Driving Pattern",
          authors: "M. Li, D. Yang, J. Tian, Y. Fan, T. Pan",
          description: "International Journal of Hydrogen Energy, 138, 273–285.",
          links: { paper: "https://doi.org/10.1016/j.ijhydene.2025.04.500" },
        },
        {
          year: "2024",
          venue: "Green Energy Intell. Transp.",
          title: "Toward Efficient Smart Management: A Review of Modeling and Optimization Approaches in Electric Vehicle–Transportation Network–Grid Integration",
          authors: "M. Li, Y. Wang, P. Peng, Z. Chen",
          description: "Green Energy and Intelligent Transportation, 100181.",
          links: { paper: "https://doi.org/10.1016/j.geits.2024.100181" },
        },
        {
          year: "2023",
          venue: "Energy Convers. Manage.",
          title: "Online Adaptive Energy Management Strategy for Fuel Cell Hybrid Vehicles Based on Improved Cluster and Regression Learner",
          authors: "M. Li, Y. Wang, P. Yu, Z. Sun, Z. Chen",
          description: "Energy Conversion and Management, 292, 117388.",
          links: { paper: "https://doi.org/10.1016/j.enconman.2023.117388" },
        },
        {
          year: "2023",
          venue: "IEEE TTE",
          title: "Topology Comparison and Sensitivity Analysis of Fuel Cell Hybrid Systems for Electric Vehicles",
          authors: "M. Li, P. Yu, Y. Wang, Z. Sun, Z. Chen",
          description: "IEEE Transactions on Transportation Electrification, 9(4), 5111–5121.",
          links: { paper: "https://doi.org/10.1109/TTE.2022.3218341" },
        },
        {
          year: "2023",
          venue: "IEEE JESTPE",
          title: "A Framework for States Co-Estimation of Hybrid Energy Storage Systems Based on Fractional-Order Theory",
          authors: "M. Li, L. Wang, Y. Wang, X. Chen, Z. Chen",
          description: "IEEE Journal of Emerging and Selected Topics in Power Electronics, 11(1), 224–233.",
          links: { paper: "https://doi.org/10.1109/JESTPE.2021.3135019" },
        },
        {
          year: "2021",
          venue: "IEEE TPEL",
          title: "Sizing Optimization and Energy Management Strategy for Hybrid Energy Storage System Using Multiobjective Optimization and Random Forests",
          authors: "M. Li, L. Wang, Y. Wang, Z. Chen",
          description: "IEEE Transactions on Power Electronics, 36(10), 11421–11430.",
          links: { paper: "https://doi.org/10.1109/TPEL.2021.3070393" },
        },
      ],
      collaborative: [
        {
          year: "2025",
          venue: "IEEE TIE",
          title: "Online Estimation of Model Parameters and State of Charge for Lithium-Ion Battery Using Multitimescale Recurrent Neural Networks",
          authors: "Z. Zhang, Y. Fan, J. Tian, H. Kuang, M. Li, T. Pan, Y. Wang, X. Liu",
          description: "IEEE Transactions on Industrial Electronics.",
          links: {},
        },
        {
          year: "2025",
          venue: "IEEE TTE",
          title: "State-of-Charge Estimation of Lithium-Ion Batteries Using an Adaptive Particle Filter Based on an Improved Particle Swarm Optimization Algorithm",
          authors: "Y. Fan, Q. Chi, X. Fang, J. Tian, M. Li, X. Liu",
          description: "IEEE Transactions on Transportation Electrification.",
          links: {},
        },
        {
          year: "2024",
          venue: "IEEE TPEL",
          title: "Predictive Energy Management for Fuel Cell Hybrid Vehicles Considering Efficiency and Safety",
          authors: "Y. Liu, M. Li, Y. Wang, Z. Sun, Z. Chen",
          description: "IEEE Transactions on Power Electronics, 39(10), 13842–13852.",
          links: {},
        },
        {
          year: "2024",
          venue: "Energy Convers. Manage.",
          title: "Capacity Configuration of Fuel Cell Hybrid Vehicles Using Enhanced Multi-Objective Particle Swarm Optimization with Competitive Mechanism",
          authors: "Y. Liu, Z. Sun, Y. Wang, M. Li, Z. Chen",
          description: "Energy Conversion and Management, 321, 119039.",
          links: {},
        },
        {
          year: "2024",
          venue: "Measurement",
          title: "A Comparative Study of Modeling and Parameter Identification for Lithium-Ion Batteries in Energy Storage Systems",
          authors: "Y. Fan, Z. Zhang, G. Yang, T. Pan, J. Tian, M. Li, X. Liu, P. Wang",
          description: "Measurement, 243, 116263.",
          links: {},
        },
        {
          year: "2024",
          venue: "Energy Technology",
          title: "Thermal Management of Proton-Exchange Membrane Fuel Cells with Enhanced Fuzzy Control via an Improved Whale Optimization Algorithm",
          authors: "Y. Shi, Z. Sun, Y. Wang, M. Li, Z. Chen",
          description: "Energy Technology, 12(6), 2400955.",
          links: {},
        },
        {
          year: "2023",
          venue: "IEEE TTE",
          title: "Lithium-Ion Battery Optimal Charging Using Moth-Flame Optimization Algorithm and Fractional-Order Model",
          authors: "Y. Wang, G. Zhao, C. Zhou, M. Li, Z. Chen",
          description: "IEEE Transactions on Transportation Electrification, 9(4), 4981–4989.",
          links: {},
        },
        {
          year: "2023",
          venue: "Energy",
          title: "Meta Rule-Based Energy Management Strategy for Battery/Supercapacitor Hybrid Electric Vehicles",
          authors: "X. Chen, M. Li, Z. Chen",
          description: "Energy, 285, 129365.",
          links: {},
        },
        {
          year: "2022",
          venue: "IEEE TITS",
          title: "Energy Management Strategy and Optimal Sizing for Hybrid Energy Storage Systems Using an Evolutionary Algorithm",
          authors: "L. Wang, M. Li, Y. Wang, Z. Chen",
          description: "IEEE Transactions on Intelligent Transportation Systems, 23(9), 14283–14293.",
          links: {},
        },
        {
          year: "2022",
          venue: "Control Eng. Practice",
          title: "An Energy Management Strategy for Hybrid Energy Storage Systems Coordinate with State of Thermal and Power",
          authors: "L. Wang, M. Li, Z. Chen",
          description: "Control Engineering Practice, 122, 105122.",
          links: {},
        },
        {
          year: "2020",
          venue: "Applied Energy",
          title: "Experimental Study of Fractional-Order Models for Lithium-Ion Battery and Ultra-Capacitor: Modeling, System Identification, and Validation",
          authors: "Y. Wang, M. Li, Z. Chen",
          description: "Applied Energy, 278, 115736.",
          links: {},
        },
        {
          year: "2020",
          venue: "Renew. Sust. Energ. Rev.",
          title: "A Comprehensive Review of Battery Modeling and State Estimation Approaches for Advanced Battery Management Systems",
          authors: "Y. Wang, J. Tian, Z. Sun, L. Wang, R. Xu, M. Li, Z. Chen",
          description: "Renewable and Sustainable Energy Reviews, 131, 110015.",
          links: {},
        },
        {
          year: "2020",
          venue: "eTransportation",
          title: "A Review of Key Issues for Control and Management in Battery and Ultra-Capacitor Hybrid Energy Storage Systems",
          authors: "Y. Wang, L. Wang, M. Li, Z. Chen",
          description: "eTransportation, 4, 100064.",
          links: {},
        },
      ],
    },
    contactEyebrow: "保持联系",
    contactHeading: "欢迎围绕新能源动力、智能储能与低空智能开展交流与合作。",
    footerNote: "使用原生 HTML、CSS 与 JavaScript 构建，托管于 GitHub Pages。",
  },
  en: {
    metaTitle: "Mince Li · Anhui University",
    metaDescription: "Mince Li is a Lecturer at Anhui University working on intelligent energy management, advanced energy storage, and low-altitude autonomous systems.",
    skipLink: "Skip to main content",
    navAbout: "About",
    navResearch: "Research",
    navExperience: "Experience",
    navPublications: "Papers",
    navContact: "Contact",
    eyebrow: "Energy · Intelligence · Control",
    name: "Mince Li",
    initials: "ML",
    heroTitle: "Lecturer · School of Electrical Engineering and Automation, Anhui University · Hefei, China",
    heroIntro: "I am a Lecturer at the <strong>School of Electrical Engineering and Automation, Anhui University</strong>. My research spans intelligent energy management, advanced energy storage, and low-altitude autonomous systems.",
    emailLabel: "Email me",
    cvLabel: "Curriculum Vitae",
    status: "Open to research collaboration and student supervision",
    aboutHeading: "About me",
    aboutParagraph1: "I received my Ph.D. in Control Science and Engineering from the Department of Automation, University of Science and Technology of China, under the supervision of Prof. Zonghai Chen. I am now a Lecturer at Anhui University, where I study state perception, intelligent decision-making, energy management, and optimal control for new-energy vehicles, UAVs, and advanced energy-storage systems.",
    aboutParagraph2: "I lead projects funded by the National Natural Science Foundation of China Young Scientists Fund (Category C) and the Anhui Provincial Natural Science Foundation Young Scientists Fund (Category C). Over the past five years, I have published more than 20 SCI-indexed papers and filed 10 invention patent applications.",
    statPapers: "SCI journal papers",
    statCitations: "Google Scholar citations",
    statPatents: "Patent applications",
    researchHeading: "Research interests",
    researchLead: "My work connects energy, perception, decision-making, and control for new-energy mobility and low-altitude autonomous systems.",
    research: [
      {
        number: "01",
        title: "New-Energy Powertrains & Intelligent Energy Management",
        description: "Modeling, energy-management strategies, and capacity optimization for fuel-cell hybrid powertrains in vehicles and UAVs.",
      },
      {
        number: "02",
        title: "Advanced Energy Storage × AI",
        description: "AI- and foundation-model-enabled state estimation, fault diagnosis, prognostics, and health management for fuel cells and batteries.",
      },
      {
        number: "03",
        title: "Low-Altitude Intelligence & Unmanned Aerial Systems",
        description: "Collaborative state estimation, embodied intelligent control, and multi-agent game decision-making for fixed-wing UAV swarms.",
      },
    ],
    experienceHeading: "Education & academic profile",
    educationHeading: "Education",
    education: [
      {
        date: "Sep 2019 — Jun 2024",
        title: "Ph.D. in Control Science and Engineering",
        place: "Department of Automation, University of Science and Technology of China",
      },
      {
        date: "Sep 2015 — Jun 2019",
        title: "B.Eng. in Electrical Engineering and Automation",
        place: "School of Electrical Engineering, Beijing Jiaotong University",
      },
    ],
    highlightsHeading: "Honors & service",
    news: [
      { date: "2026", text: "First Prize, Teaching Achievement Award of the China Simulation Federation." },
      { date: "2025", text: "Best Paper Award at ICPRE; Session Chair at the ICPRE international conference." },
      { date: "2024", text: "First Prize in Anhui University's teaching demonstration for newly appointed faculty." },
      { date: "Honors", text: "CAS President's Excellence Award and four National Scholarships across undergraduate and graduate study." },
      { date: "Service", text: "IEEE Member; reviewer for IEEE TITS, IEEE TTE, IEEE TVT, Applied Energy, RSER, EAAI, and other SCI journals." },
      { date: "Societies", text: "Member of the System Simulation Technical Committee, Chinese Association of Automation, and the Simulation Technology Application Committee, China Simulation Federation." },
      { date: "Teaching", text: "Microcontroller Principles and Applications, Introduction to AI, Communication Principles, and Intelligent Battery Management." },
    ],
    publicationsHeading: "Selected journal publications",
    allPublications: "Complete list on Google Scholar",
    primaryGroup: "First / corresponding author",
    collaborativeGroup: "Collaborative work",
    authorNote: "* Corresponding author",
    linkPaper: "Paper",
    linkCode: "Code",
    linkProject: "Project",
    publications: null,
    contactEyebrow: "Get in touch",
    contactHeading: "I welcome conversations and collaborations in intelligent energy, advanced storage, and low-altitude autonomy.",
    footerNote: "Built with plain HTML, CSS, and JavaScript. Hosted on GitHub Pages.",
  },
};

// Publication titles are already in English; reuse the same verified records for both languages.
window.SITE_CONTENT.en.publications = window.SITE_CONTENT.zh.publications;
